server.port=8080

# ===============================
# SUPABASE POSTGRES
# ===============================
spring.datasource.url=jdbc:postgresql://db.dvgfofdofnfxfcklccwc.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# JWT
# ===============================
jwt.secret=KcP7cT+WvLJkE5sZ8kZqPp9yR4n1l9FzQzZc6qA1sJcV0m3xH7wR9cF5nG1yB8M
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# ===============================
# MAIL (optional)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harshanand0220@gmail.com
spring.mail.password=wyzxohikhlutechh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# CORS
# ===============================
app.cors.allowed-origins=https://your-frontend-url
app.cors.allow-credentials=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
spring.datasource.hikari.data-source-properties.prepareThreshold=0



